person :
name : john Doe
address :
Street : 123 Main St
City : Anytown
Country : USA
Preferenes :
hobbies :
- reading 
- hiking
- coding
favorite - color : blue
employment :
Position: software engineer
company : TechCO Inc
