name: Code Scanning

on:
  push:
    branches:
      - main

jobs:
  code-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Code Scanning
        uses: github/codeql-action@v2
        with:
          languages: javascript, python, java  # Define the languages to scan
