name: Java Lint Check

on: [push, pull_request]  # Trigger the workflow on pushes and pull requests

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # Checkout the code

      - name: Set up JDK  # Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Choose the appropriate Java version
          distribution: 'adopt'

      - name: Run Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.44/checkstyle-8.44-all.jar
          java -jar checkstyle-8.44-all.jar -c path/to/your/checkstyle.xml path/to/your/java/source/files
